[package]
name = "web"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
wgpu = { workspace = true }
wgpu-cross = { workspace = true }

wasm-bindgen = "0.2.100"
web-sys = "0.3.77"
console_error_panic_hook = "0.1.7"
wasm-bindgen-futures = "0.4.50"
